#ifndef INC_NETDEF_H
#define INC_NETDEF_H
USAF_START

#define USAF_NET_MOD_BASE			0
#define USAF_NET_MOD_HTTPD			1	

#define	USAF_INIT_OK				0
#define USAF_INIT_NULL_INFO			-1
#define USAF_INIT_NULL_LOGOBJECT	-2

#define USAF_STARTUP_WITHOUTINIT	-1
#define USAF_STARTUP_LISTENFAIL		-2

#define USAF_DEFAULT_TIMEOUT		3

#define USAF_NET_DEFAULT_LISTEN_SIZE 10

#define USAF_EMPTY_ZERO				0

#define USAF_LOCALHOST				"127.0.0.1"

USAF_END
#endif
